@startuml
top to bottom direction

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(user, "Клиент", "Пользователь банка")
Person(callAgent, "Сотрудник кол-центра", "Обрабатывает заявки новых клиентов, звонит для уточнения условий")
Person(backOffice, "Сотрудник бэк-офиса", "Обрабатывает заявки в АБС")

System(deposit, "Система депозитов", "Управление депозитами")
System(abs, "АБС", "Данные клиентов, счета, работа с заявками, депозитные продукты")
System(crm, "CRM система кол-центра", "Управление заявками новых клиентов")

System_Ext(smsGateway, "SMS Gateway", "Шлюз для SMS-сообщений")

Rel(user, deposit, "Подает заявку на депозит", "HTTPS")
Rel(user, deposit, "Подает заявку на депозит (возможно с персонализированными ставками)", "HTTPS")
Rel(callAgent, crm, "Обрабатывает заявки новых клиентов")
Rel(backOffice, abs, "Обрабатывает заявки в АБС")

Rel(deposit, abs, "Получает данные клиентов или ставок, создает заявки", "HTTPS")
Rel(deposit, crm, "Передает заявки новых клиентов", "Kafka")
Rel(crm, abs, "Создает заявки после обработки", "HTTPS")
Rel(abs, smsGateway, "Отправка SMS", "HTTPS")

@enduml
