@startuml C4_Container_Diagram
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(customer, "Customer", "A customer using the Bank")
System_Ext(to, "Telecom Operator", "", "")

System_Boundary(s1, "Warm House System") {
    Person(boe, "Back Office Employee", "Deposit Credit")
    Person(foe, "Front Office Employee", "Working with customer")
    Container(abs, "Automated banking system", "Delphi + Oracle", "")
    Container(cc, "Call Center", "React.js + Java Spring Boot + PostgreSQL.", "")
    Container(pcc, "Partner Call Center", "", "Outsource")
    Container(sms, "SMS GateWay", "", "")
    Container(site, "Site", "", "Only marketing information")
}

Rel(sms, to, "Send sms", "")

Rel(customer, site, "Observe marketing info", "")
Rel(customer, foe, "Came to an office", "")
Rel(customer, cc, "Request: credit, deposit e.t.c.", "")
Rel(customer, pcc, "Request: credit, deposit e.t.c.", "")

Rel(foe, boe, "Request: credit, deposit e.t.c.", "")

Rel(foe, abs, "Request: credit, deposit e.t.c.", "")
Rel(boe, abs, "Request: credit, deposit e.t.c.", "")
Rel(cc, abs, "Request: credit, deposit e.t.c.", "")

Rel(abs, sms, "Push notions about credit & deposit", "")

Rel(cc, foe, "Push notions about credit & deposit", "")
Rel(pcc, foe, "Push notions about credit & deposit", "")

@enduml