@startuml
top to bottom direction

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(user, "Клиент", "Пользователь банка")
Person(callAgent, "Сотрудник кол-центра", "Обрабатывает заявки новых клиентов, звонит для уточнения условий")
Person(backOffice, "Сотрудник бэк-офиса", "Обрабатывает заявки в АБС")
Person(frontOffice, "Менеджер отделения", "Заводит заявки в АБС")

System(credit, "Система кредитов", "Управление кредитами")
System(abs, "АБС", "Автоматизированная банковская система")
System(crm, "CRM система кол-центра", "Управление заявками новых клиентов")
System(creditPipeline, "Кредитный конвейер", "Система обработки кредитных заявок на базе Camunda BPM")
System(scoringSystem, "Система кредитного скоринга", "Расчет кредитного рейтинга клиентов")
System(internetBank, "Интернет-банк", "Система дистанционного банковского обслуживания")
System(website, "Сайт банка", "Публичный сайт для новых клиентов")

System_Ext(smsGateway, "SMS Gateway", "Шлюз для SMS-сообщений")
System_Ext(bki, "БКИ", "Бюро кредитных историй")

Rel(user, internetBank, "Подает заявку на кредит", "HTTPS")
Rel(user, internetBank, "Подает заявку на кредит (возможно с персонализированными ставками)", "HTTPS")
Rel(callAgent, crm, "Обрабатывает заявки новых клиентов")
Rel(backOffice, abs, "Обрабатывает заявки в АБС")
Rel(credit, abs, "Получает данные клиентов или ставок, создает заявки", "HTTPS")
Rel(credit, crm, "Передает заявки новых клиентов", "Kafka")
Rel(crm, abs, "Создает заявки после обработки", "HTTPS")
Rel(abs, smsGateway, "Отправка SMS", "HTTPS")


Rel(user, frontOffice, "Подает заявку на кредит")
Rel(frontOffice, credit, "Заводит заявку в систему")
Rel(credit, creditPipeline, "Обрабатывает кредитные заявки")
Rel(user, internetBank, "Запрашивает предодобренные предложения")
Rel(internetBank, credit, "Запрашивает данные или передает заявки", "HTTPS")
Rel(website, credit, "Запрашивает условия кредита", "HTTPS")
Rel(credit, scoringSystem, "Запрашивает рейтинг клиент", "HTTPS")
Rel(scoringSystem, bki, "Запрашивает кредитную историю", "HTTPS")
Rel(smsGateway, user, "SMS-код подтверждения", "SMS")

@enduml
